### ISSUE TITLE
US02 - Identificar Palavra

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#10]
## Descrição
Eu, como Educador, desejo que a aplicação possa identificar uma palavra a partir de um conjunto de letras.

## Critérios de Aceitação
- [ ] Identificar múltiplas letras ao mesmo tempo
- [ ] Concatenação das letras para a formação de uma palavra (string)

## Comportamento esperado
Ao identificar duas ou mais letras por meio da câmera, a aplicação poderá identificar uma palavra ao juntá-las.

**Comment by Rhuancpq** [comment]
`https://medium.com/arjs/area-learning-with-multi-markers-in-ar-js-1ff03a2f9fbe` blog do AR.js explicando _multi-markers_

**Comment by Rhuancpq** [comment]
https://stackoverflow.com/questions/44799413/how-to-detect-when-a-marker-is-found-in-ar-js contém informações acerca de como acessar o marcador usando html puro

**Comment by Rhuancpq** [comment]
https://github.com/jeromeetienne/AR.js/blob/master/three.js/src/markers-area/threex-armultimarkerlearning.js alguns pedaços do código do multimarker utilizam algumas propriedades do marker pra pegar a posição dele

**Comment by Rhuancpq** [comment]
vide linhas 89 a 92

**Comment by Rhuancpq** [comment]
https://aframe.io/docs/0.9.0/components/rotation.html#relative-rotation tópico útil sobre rotação de objetos no aframe
