### ISSUE TITLE
US05 - Marcadores Físicos

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2019.2-ArBC#110]
## Descrição
Eu como usuário desejo ter marcadores físicos para poder montar palavras para serem lidas com o App.

## Critérios de Aceitação
- [x] Consultar os preços de impressão
- [x] Adquirir os marcadores

## Recomendações
* Cards em algum material resistente e que não seja muito maleável. Como por exemplo PVC.
* Tamanho 6 x 6 cm
* Bordas devem ser **PRETAS**

## Possível solução
Pesquisar por gráficas para termos vários orçamentos e escolher o melhor

**Comment by igor-paiva** [comment]
Impressão em PVC 9x9 cm na gráfica Betel, na Ceilândia, ficou R$ 280,00.

Porém com a diminuição do tamanho, deve sair mais barato

Número da gráfica: 61 3374-9547

**Comment by igor-paiva** [comment]
Entrei em contato com a gráfica Betel e pedi a impressão de 7 marcadores para testes. 

Ficarão prontos nessa semana

**Comment by jlucassr** [comment]
Solicitei alguns stickers para a apresentação, por questão de material para testes foi feitos, a US foi cumprida.
