### ISSUE TITLE
Conseguir acessar patterns localmente

### ISSUE THREAD

**Issue by SergioAlmeidaCiprianoJr** [fga-eps-mds/2019.2-ArBC#112]
**Descreva o bug**

Não poder acessar os patts localmente. Ex:

```
public patternUrl(letter: string) {
      return `@/src/assets/patterns/pattern-${letter}.patt`;
}
``` 
- Lembrando que esse exemplo é para auxiliar a visualização do problema, mas é quase certeza que não acessaremos dessa maneira. Afinal, está errada.

O que estamos usando:

```
private mediaBaseUrl: string = 'https://raw.githubusercontent.com/fga-eps-mds/2019.2-ArBC/test_patterns';
.
.
.
public patternUrl(letter: string) {
      return `${this.mediaBaseUrl}/src/assets/patterns/pattern-${letter}.patt`;
}
``` 

**Como reproduzir**

Acessar localmente os patts e abrir o console

**Comportamento esperado**

Caso esse problema seja solucionado é provável que também possamos solucionar o problema de chamada de patts. Atualmente não estamos conseguindo chamar 52 e o ideal seria chamar mais ou menos uns 60 (englobaria todas as vogais repetidas 3x). Se o problema de memória ao chamar os patts for corrigido sem acessar localmente, também será aceito.

**Screenshots**

Erro de acesso local:

![Captura de tela de 2019-11-06 18-17-24](https://user-images.githubusercontent.com/36544528/68338843-1db0c180-00c2-11ea-9c94-ed67cf1f8fde.png)

**Informações adicionais**

Links úteis relacionados à esse erro em específico: 

https://github.com/naptha/tesseract.js/issues/100
https://github.com/kripken/sql.js/issues/113
https://github.com/seikichi/tiff.js/issues/37

Link útil relacionado ao erro de marcadores repetidos:

 https://github.com/jeromeetienne/AR.js/issues/556 (A solução dessa issue é quase que nula, mas é interessante ver que o erro pode não estar na nossa implementação)

**Comment by SergioAlmeidaCiprianoJr** [comment]
Outra alternativa que irei testar é de colocar os patterns no back e chama-los da mesma forma que os gifs. Como eles são bem pequenos não devem interferir muito no desempenho da aplicação e, como estamos na reta final, qualquer alternativa é válida para ser testada.

![](http://giphygifs.s3.amazonaws.com/media/gw3MYmhxEv8T52ow/giphy.gif)

**Comment by Rhuancpq** [comment]
Vamos fazer a integração dos `.patts` no back com o front por meio dessa issue, isso culmina:
- [ ] Configurar nova store
- [ ] Testar o módulo da store

![](https://media.giphy.com/media/elhmwUMsAUbScKLLzl/giphy.gif)

**Comment by SergioAlmeidaCiprianoJr** [comment]
A integração e as alterações feitas na isssue  https://github.com/fga-eps-mds/2019.2-ArBC-API/issues/26 conflitam com a biblioteca do arjs.

O motivo possível do conflito é a maneira que disponibilizamos os patts no back. No github, pegamos o link do raw, chamamos pelo seu url e efetuamos seu download. No back, chamamos pelo link e já efetuamos diretamente o download.

Pelo fato do tempo estar apertado não vale a pena investir mais nessa issue, visto que por mais que apresentasse melhorias, o motivo do erro ainda é especulação. Como essas alterações não impedem a aplicação de funcionar vamos dropar as alterações e seguir finalizando as demais isssues.

![](https://media.giphy.com/media/sChf4Eo55W8x2/giphy.gif)

**Comment by igor-paiva** [comment]
Aparentemente é um problema com como a biblioteca espera o URL. E não houve nenhuma solução efetiva elaborada. 

Como aa requisições serão feitas de qualquer jeito, da forma que está funciona bem e da mesma forma, afetando apenas o ambiente de desenvolvimento no acesso offline.
