### ISSUE TITLE
US04 - Visualizar Imagem

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#12]
## Descrição
Eu, como Educador, desejo que a aplicação mostre uma imagem por meio de realidade virtual ao identificar uma palavra válida.

## Critérios de Aceitação
- [ ] Verificar correspondência da imagem requisitada no projeto
- [ ] Configurar posicionamento da imagem
- [ ] Mostrar imagem ao usuário corretamente

## Comportamento esperado
Ao identificar e validar a palavra, a aplicação mostrará uma imagem correspondente por meio de realidade aumentada ao usuário.

**Comment by Rhuancpq** [comment]
https://github.com/jeromeetienne/AR.js/tree/master/three.js

**Comment by SergioAlmeidaCiprianoJr** [comment]
https://github.com/u4bi-dev/simple-ar.js um exemplo simples de aplicação do Ar.js feito pelo jeromeetienne
