### ISSUE TITLE
Estudo de Javascript

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#14]
## Descrição 
Estudo básico sobre javascript, visto que a tecnologia a ser utilizada para o front-end será o Vue.js.

## Materiais
Getting Started - Javascript, Tableless. Disponível em: <https://tableless.github.io/iniciantes/manual/js/>
Vue Guide, Vue. Disponível em: <https://vuejs.org/v2/guide>

**Comment by jlucassr** [comment]
Os MDS se dedicaram as últimas 2 sprints ao estudos das tecnologias, e de acordo com o quadro de conhecimento deles, acho relevante fechar a issue já que a tarefa foi feita e que futuros estudos serão realizados.

Link do quadro de conhecimento:
https://docs.google.com/spreadsheets/d/1imkSJRYzlSGxXy7ntmvbrUfCfvLAZWlUqaUm5qwuW64/edit?usp=sharing

![](https://media.giphy.com/media/fhAwk4DnqNgw8/giphy.gif)
