### ISSUE TITLE
URL de início da PWA inexistente

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2019.2-ArBC#140]
**Descrição**
O URL de abertura da PWA está com uma rota não existente, fazendo com que não seja possível abrir a aplicação como PWA

**Como reproduzir**
Etapas para reproduzir o bug:
1. Vá para o endereço do app no navegador
2. Adicione o App no dispositivo
3. Execute-o
4. Veja erro

**Comportamento esperado**
Abrir na página inicial do app

**Screenshots**

![photo_2019-11-27_11-21-43](https://user-images.githubusercontent.com/51242776/69731207-3ed86100-1108-11ea-8eb4-ce318fba72c1.jpg)

**Comment by joenio** [comment]
mesmo erro comigo em Android 9 no Chrome 78.0.3904.108
