### ISSUE TITLE
Roadmap de Projeto

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#20]
## Descrição 
Definir roadmap para entrega de features do projeto ao longo do semestre.

## Referências
Roadmap: o que é e como fazer o seu, Endeavor Brasil. Disponível em: <https://endeavor.org.br/estrategia-e-gestao/roadmap/> Acesso em: 07/09/2019.

**Comment by jlucassr** [comment]
Documento criado e adicionado a Wiki.
Link: https://jlucassr.github.io/ArBC-Pages/eps/roadmap/
