### ISSUE TITLE
FT02 - Banco de Dados

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#22]
## Descrição
Criar modelo para banco de dados a ser usado na aplicação com MongoDB no back-end Django.
Cada modelo deve incluir o nome e o endereço da imagem correspondente àquele modelo. (2 campos)

## Critérios de Aceitação
- [x] Configurar MongoDB
- [x] Criar modelo para letra
- [x] Criar modelo para palavra

## Referências
MongoDB Tutorials, MongoDB Docs. Disponível em: <https://docs.mongodb.com/manual/tutorial/> 
MongoDB Tutorial, MongoDB Docs. Disponível em: <https://www.tutorialspoint.com/mongodb/index.htm>

**Comment by Rhuancpq** [comment]
Issue espelho no back-end foi fechada
