### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#23]
## Descrição 
Criar um protótipo de baixa fidelidade para visualização da aplicação.

## Referências
O que são protótipos de alta e baixa fidelidade, Startup Sorocaba. Disponível em: <https://startupsorocaba.com/startup-sorocaba-o-que-sao-prototipos-de-baixa-e-alta-fidelidade/>

**Comment by jlucassr** [comment]
Os alunos de MDS fizeram um protótipo muito bom para ser considerado de baixa fidelidade, contudo algumas alterações serão feitas, por isso a Issue foi alterada de nome.
