### ISSUE TITLE
Estudo de Python

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#24]
## Descrição 
Estudo básico sobre python, visto que a tecnologia a ser utilizada para o back-end será o Django.

## Materiais
Getting Started with Django, Django. Disponível em: <https://www.djangoproject.com/start/>
Introdução, Django Girls. Disponível em: <https://tutorial.djangogirls.org/pt/>

**Comment by jlucassr** [comment]
Os MDS se dedicaram as últimas 2 sprints ao estudos das tecnologias, e de acordo com o quadro de conhecimento deles, acho relevante fechar a issue já que a tarefa foi feita e que futuros estudos serão realizados.

Link do quadro de conhecimento:
https://docs.google.com/spreadsheets/d/1imkSJRYzlSGxXy7ntmvbrUfCfvLAZWlUqaUm5qwuW64/edit?usp=sharing

![](https://media.giphy.com/media/IqFH0yMll9wl2/source.gif)
