### ISSUE TITLE
Elaborar Roadmap de Devops

### ISSUE THREAD

**Issue by lucianosz7** [fga-eps-mds/2019.2-ArBC#29]
## Descrição 
Definir e documentar as tarefas a serem desempenhadas pelo devops

## Critérios de aceitação
- [x] Roadmap do devops deve estar na wiki do projeto
- [x] Documentar de forma objetiva todas as tarefas a serem desempenhadas pelo devops

**Comment by jlucassr** [comment]
O documento foi criado e adicionado a Wiki.
Link: https://jlucassr.github.io/ArBC-Pages/eps/roadmapDevops/
