### ISSUE TITLE
Elaborar o Roadmap de Arquitetura

### ISSUE THREAD

**Issue by lucianosz7** [fga-eps-mds/2019.2-ArBC#30]
## Descrição 
Elaborar o roadmap de arquitetura para que seja possível ter uma visão ampla de todas as tarefas relacionadas a arquitetura do projeto.

## Critérios de aceitação
- [x] Roadmap de Arquitetura deve estar na wiki do projeto
- [x] Documentar de forma objetiva todas as tarefas a serem desempenhadas pelo arquiteto

**Comment by jlucassr** [comment]
O documento foi criado mas um PR apropriado não foi providenciado.
Mas por cumprir as tarefas da issue, será fechada

**Comment by jlucassr** [comment]
Link: https://jlucassr.github.io/ArBC-Pages/eps/roadmapArquiteto/
