### ISSUE TITLE
Elaborar Roadmap do Scrum Master

### ISSUE THREAD

**Issue by lucianosz7** [fga-eps-mds/2019.2-ArBC#31]
## Descrição 
Elaborar o documento para que todas as tarefas relacionadas ao Scrum master sejam documentadas.
## Critérios de aceitação
- [x] Roadmap do Scrum Master deve estar na wiki do projeto
- [x] Documentar de forma objetiva todas as tarefas a serem desempenhadas pelo scrum master

**Comment by jlucassr** [comment]
O documento se encontrar na branch 'roadmap' juntamente com o roadmap do projeto.

**Comment by jlucassr** [comment]
Documento criado e adicionado a wiki:
Link: https://jlucassr.github.io/ArBC-Pages/eps/roadmapScrumMaster/
