### ISSUE TITLE
Estudar API de Realidade Aumentada

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#36]
## Descrição 
Estudar possíveis opções de API para uso como base no projeto.
Tomar em conta as reuniões que já fizemos e sobre a tecnologia utilizada para cada um, visot que o projeto usará o Vue.js.

## Referências
Jandig ARte. Disponível em: <https://github.com/memeLab/ARte/> Acesso em: 16 set 2019.
AR.js, jeromeetiene. Disponível em: <https://github.com/jeromeetienne/AR.js/> Acesso em: 16 set 2019.
WITHIN. Disponível em: <https://madewithvuejs.com/within> Acesso em: 16 set 2019.
Creating Augmented Reality with AR.js and A-Frame, aframe. Disponível em: <https://aframe.io/blog/arjs/> Acesso em: 16 set 2019.

**Comment by Rhuancpq** [comment]
esse arquivo _base_ `"src/ARte/core/jinja2/core/base.jinja2" ` no repositório do Jandig, parece que contém tudo que envolve o Ar.js e que é usado no projeto.

**Comment by thiagolopess** [comment]
Gerador dos patterns:

https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.htm

**Comment by Rhuancpq** [comment]
Aframe: https://aframe.io/docs/0.9.0/introduction/installation.html

**Comment by Rhuancpq** [comment]
https://github.com/mayognaise/aframe-gif-shader suporte para gifs transparentes no aframe

**Comment by thiagolopess** [comment]
Aframe e ARJS: https://aframe.io/blog/arjs/

**Comment by thiagolopess** [comment]
Components aframe: https://aframe.io/docs/master/components/material.html

**Comment by thiagolopess** [comment]
Eventos quando um marker é encontrado/perdido: https://stackoverflow.com/questions/44799413/how-to-detect-when-a-marker-is-found-in-ar-js

**Comment by Rhuancpq** [comment]
https://github.com/aframevr/aframe/blob/master/src/systems/camera.js Src do funcionamento da camera no aframe
