### ISSUE TITLE
Planejar apresentação da Release 1

### ISSUE THREAD

**Issue by SergioAlmeidaCiprianoJr** [fga-eps-mds/2019.2-ArBC#41]
## Descrição 
Criar apresentação para a Release 1.

## Critérios de aceitação

- [x] Definição do projeto
- [x] Apresentar objetivos do projeto
- [x] Descrever documentos de EPS
- [x] Descrever documentos de MDS
- [x] Descrever ferramentas utilizadas

**Comment by jlucassr** [comment]
O Grupo 5 - ArBC apresentou o trabalho na Release 1 do dia 08 de Outubro de 2019. Com isso a Issue está fechado.
