### ISSUE TITLE
Correção das Patterns

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#48]
## Descrição 
Corrigir fundo das patterns para que não haja conflitos entre elas.

## Critérios de aceitação
- [ ] Assegurar que as patterns não sejam confundidas entre si
- [ ] Manter patterns reconhecíveis (não poluir demais)

## Referências
https://github.com/artoolkit/artoolkit-docs/blob/master/3_Marker_Training/marker_training.md
https://github.com/artoolkit/jsartoolkit5

**Comment by Rhuancpq** [comment]
https://github.com/artoolkit/artoolkit-docs/blob/master/3_Marker_Training/marker_training.md Link para documentação do artoolkit, o melhor jeito de corrigir os marcadores é saber como eles são lidos

**Comment by Rhuancpq** [comment]
https://github.com/artoolkit/jsartoolkit5 Mais um, esse, se não me engano é o que o AR.js usa
