### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#6]
## Descrição
Criar backlog de produto do projeto.
## Objetivo
Criar uma lista priorizada de User Stories que será usada e atualizada ao decorrer do projeto durante as sprints.
## Referências
The Scrum Insitute. The Scrum Product Backlog. Disponível em: <https://www.scrum-institute.org/The_Scrum_Product_Backlog.php> Acessp em: 28/08/2019.

**Comment by jlucassr** [comment]
O documento se encontra nesse link:
https://docs.google.com/spreadsheets/d/1wnT7UdFTu3rCG1Sdsv5C9kS0KtDUBNw9O5ffhebFGvI/edit?usp=sharing
