### ISSUE TITLE
Identificação de palavras com múltiplas letras iguais

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2019.2-ArBC#88]
## Descrição 
Implementar uma forma de com vários marcadores iguais para uma palavra, identificar a palavra correspondente. Atualmente a aplicação ignora a presença de marcadores iguais, impossibilitando a leitura de palavras como "Arara", com 3 letras "A" e duas letras "R".

## Critérios de aceitação
- [ ] Fazer a leitura de palavras com múltiplas letras iguais
- [ ] Método testado

## Ajuda no Desenvolvimento
Evento lançado pelo **a-marker** quando o marcador é identificado:

No a-marker adicione o evento:

`@markerFound="alguma_função($event)"`

O `$event` passa o que é retornado do evento. Exemplo:
![MarkerFoundEvent](https://user-images.githubusercontent.com/51242776/66680362-cb0cf280-ec46-11e9-9c7b-d20a0516dae3.png)

**Comment by Rhuancpq** [comment]
O motivo por que esse bug ocorre, tem a ver com a forma que funciona o aframe + ar.js e, a forma como o ar.js obtém os marcadores, no caso, o que acontece é que apenas o ultimo marcador de uma lista (lista de todos os que foram lidos na câmera) tem sua posição configurada e colocado em estado visível

**Comment by SergioAlmeidaCiprianoJr** [comment]
Lista de patterns duplicadas que foram testadas e estão funcionando:
(baseado nas alterações da branch test_patterns)
- A
- D (alterei demais e deu ruim)
- R

**Comment by marcelog5** [comment]
Por algum motivo se colocado duas letras iguais, só que uma de cabeça para baixo enquanto a outra em pé o reconhecimento das duas letras falham, mostrando nenhuma delas.
