### ISSUE TITLE
Testar funcionamento da leitura

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2019.2-ArBC#89]
## Descrição 
Testar ao máximo, incansavelmente, o funcionamento da leitura de letras. Com objetivo de identificar possíveis falhas e formas de aprimoração do projeto como um todo.

## Critérios de aceitação
- [x] Estar no mínimo cansado
- [x] Obtido algum resultado, seja qual for

**Comment by jlucassr** [comment]
Foram feitos testes com os marcadores, então será fechado a issue
