### ISSUE TITLE
Interface Gráfica

### ISSUE THREAD

**Issue by SergioAlmeidaCiprianoJr** [fga-eps-mds/2019.2-ArBC#91]
## Descrição 
Como o projeto ainda não tem uma interface gráfica pré definida ,estando centrado na App.vue, com apenas a câmera na interface. Assim, é necessário criar uma interface na Home.vue que seja amigavel a um usuário preferencialmente jovem e que se relacione com a App.vue.

## Critérios de aceitação

- [ ] Home.vue
- [ ] Interface funcional
- [ ] Interface de simples utilização
- [ ] Redirecionamento para a App.vue funcionando
- [ ] Modularização do código
- [ ] Download dos marcadores disponível pela própria interface

**Comment by SergioAlmeidaCiprianoJr** [comment]
Devido a problemas técnicos com a integração do vuetify ao projeto pensamos em utilizar apenas CSS. O conflito estava ocorrendo com a identificação do 'vuetify/lib'. Sendo assim, para evitar futuros conflitos com Ar e TS, eu e o Marcelo estamos optando por nos aventurar pelo CSS.

![](https://media.giphy.com/media/9Sc2AdK0QvgLm/giphy.gif)

**Comment by SergioAlmeidaCiprianoJr** [comment]
Após recobrarmos a sanidade vimos que css puro é uma ideia muito torta. Então, como o vuetify teve conflitos com o aframe, optamos pelo bootstrap-vue. Infelizmente, ele também deu conflitos e a câmera não está sendo acessada fora da App.vue. O objetivo é fazer a Home.vue e a Camera.vue de forma isolada, mas por enquanto iremos tentar utilizando apenas a App.vue igual anteriormente.

![](https://media.giphy.com/media/TseBjMu53JgWc/giphy.gif)

**Comment by igor-paiva** [comment]
Devido aos problemas com o Vuetify e com o Vue Bootstrap, tivemos que partir pra outra lib de componentes... Agora vamos usar o [Vue Material](https://vuematerial.io/).

A instalação é simples, apenas adicionar o pacote ao projeto (o container deve estar rodando):

```
docker exec -it ArBC-APP npm install vue-material --save
```

Vamos importar os componentes assim que precisarmos deles, dessa forma vamos deixar a aplicação mais leve. Para importar vamos cirar um arquivo para isso:
`src/vueMaterialComponents.ts`
```
import Vue from 'vue';
import 'vue-material/dist/theme/default.css';
import 'vue-material/dist/vue-material.min.css';
import {
  MdButton,
  MdTabs,
} from 'vue-material/dist/components';

Vue.use(
  MdButton,
  MdTabs,
);
```
No `src/main.ts`:
```
import './vueMaterialComponents';
```

Nos componentes não é preciso declarar os componentes, apenas chamá-los, lembrem-se que é usando o _kebab case_. Exemplo:
```
<md-button>
  CLICK
</md-button>
```

Para evitar problemas com os pacotes e/ou mudanças na branch que já foi bastante modificado, iremos apagar a branch atual de interface gráfica e criar uma nova a partir da develop.

Agora vai dar tudo certo!! :wink:

![](https://thumbs.gfycat.com/WearyShadyBobwhite-size_restricted.gif)

**Comment by marcelog5** [comment]
Por algum motivo no arquivo components.ts se for utilizado o seguinte padrão:
```
Vue.use(
  MdButton,
  MdTabs,
); 
```
somente o primeiro é importado de maneira correta.

Olhando a documentação foi visto que o padrão correto a ser escrito é:
```
Vue.use(MdButton);
Vue.use(MdTabs);
Vue.use(MdCard);
```
O que solucionou alguns problemas.

![](https://media.giphy.com/media/3o6fIPsLQ8iKAgwsU0/giphy.gif)

**Comment by SergioAlmeidaCiprianoJr** [comment]
Enquanto estávamos corrigindo erros na interface descobrimos um novo erro. Após a inserção do vue-material o gif passou a ser levemente deslocado para baixo. Segue imagem do erro:

![Captura de tela de 2019-10-27 14-42-59](https://user-images.githubusercontent.com/36544528/67639131-b5e0c680-f8ca-11e9-994e-f14c66618634.png)

Estamos testando algumas alternativas na Camera.vue, já que se der para resolver sem afetar o restante da aplicação será muito mais limpo.

![](http://giphygifs.s3.amazonaws.com/media/cWYl8greeYQSs/giphy.gif)

**Comment by SergioAlmeidaCiprianoJr** [comment]
Existe 3 detalhes muito importantes no funcionamento da interface. O primeiro é a maneira que é colocado os links na ToolBar. A maneira abaixo é utilizando o vue-router:

```
@click="$router.push('./camera')"
```

Esse método causa os conflitos descritos no comentário acima, então está sendo substituído por:

```
href="./camera"
```

O segundo detalhe, que não é exclusivo da interface, é que a App.vue deve estar sem divs.

Desse jeito está Ok:
```
<template>
  <router-view/>
</template>
```

Desse jeito não está Ok:
```
<template>
  <div class="page-container" align="center">
    <router-view/>
  </div>
</template>
```

Por fim, a maneira que utilizamos para corrigir o erro de deslocamento relatado no comentário anterior foi de importar localmente o vue-material ao invés de globalmente. Dessa maneira, a Camera.vue não é afetada pelo resto da aplicação e vice-versa.

![](https://media.giphy.com/media/zEJRrMkDvRe5G/giphy.gif)
